apiVersion: v2
name: directport
description: DirectPort — сервис импорта товаров в Россию
type: application
version: 0.1.0
appVersion: '1.0.0'
dependencies:
  - name: postgresql
    version: 18.5.16
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 25.3.10
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
