apiVersion: v1
kind: Service
metadata:
  name: {{ include "directport.fullname" . }}-client-bot
  labels:
    {{- include "directport.labels" . | nindent 4 }}
    app.kubernetes.io/component: client-bot
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.clientBot.port }}
      targetPort: {{ .Values.clientBot.port }}
      protocol: TCP
  selector:
    {{- include "directport.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client-bot
