upstream stage_ingress_http {
    server 127.0.0.1:32080;
    keepalive 64;
}

server {
    listen 80;
    server_name coreimport.ru;

    location / {
        proxy_pass http://stage_ingress_http;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host coreimport-landing.lab42-stg.work;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name admin-access.coreimport.ru;

    location / {
        proxy_pass http://stage_ingress_http;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host coreimport-admin.lab42-stg.work;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
