export enum ErrorCode {
  FILE_REQUIRED = 'FILE_REQUIRED',
  UNSUPPORTED_FORMAT = 'UNSUPPORTED_FORMAT',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  INVALID_STATUS_FOR_REPROCESS = 'INVALID_STATUS_FOR_REPROCESS',
  INVALID_STATUS_FOR_REVIEW = 'INVALID_STATUS_FOR_REVIEW',
  INVALID_STATUS_FOR_REJECT = 'INVALID_STATUS_FOR_REJECT',
  PARSING_FAILED = 'PARSING_FAILED',
  PROCESSING_FAILED = 'PROCESSING_FAILED',
}
