/**
 * Статический справочник стран мира (OKSMT / ISO 3166-1).
 * Используется для селекта страны происхождения и для резолва CU-кодов
 * из TNVEDALL в имена стран (антидемпинговые/преференциальные ставки).
 *
 * `code` — OKSMT / ISO 3166-1 numeric, 3 цифры, с ведущими нулями.
 * `nameRu` — краткое наименование из ОКСМ (верхний регистр, как в исходном справочнике TKS).
 * `nameFullRu` — полное официальное наименование.
 */
export interface OksmtCountry {
  code: string;
  alpha2: string | null;
  alpha3: string | null;
  nameRu: string;
  nameFullRu: string | null;
  nameEn: string | null;
}

export const OKSMT_COUNTRIES: readonly OksmtCountry[] = [
  { code: '004', alpha2: 'AF', alpha3: 'AFG', nameRu: 'АФГАНИСТАН', nameFullRu: 'ПЕРЕХОДНОЕ ИСЛАМСКОЕ ГОСУДАРСТВО АФГАНИСТАН', nameEn: 'Afghanistan' },
  { code: '008', alpha2: 'AL', alpha3: 'ALB', nameRu: 'АЛБАНИЯ', nameFullRu: 'РЕСПУБЛИКА АЛБАНИЯ', nameEn: 'Albania' },
  { code: '010', alpha2: 'AQ', alpha3: 'ATA', nameRu: 'АНТАРКТИДА', nameFullRu: 'АНТАРКТИДА', nameEn: 'Antarctica' },
  { code: '012', alpha2: 'DZ', alpha3: 'DZA', nameRu: 'АЛЖИР', nameFullRu: 'АЛЖИРСКАЯ НАРОДНАЯ ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', nameEn: 'Algeria' },
  { code: '016', alpha2: 'AS', alpha3: 'ASM', nameRu: 'АМЕРИКАНСКОЕ САМОА', nameFullRu: 'АМЕРИКАНСКОЕ САМОА', nameEn: 'American Samoa' },
  { code: '020', alpha2: 'AD', alpha3: 'AND', nameRu: 'АНДОРРА', nameFullRu: 'КНЯЖЕСТВО АНДОРРА', nameEn: 'Andorra' },
  { code: '024', alpha2: 'AO', alpha3: 'AGO', nameRu: 'АНГОЛА', nameFullRu: 'РЕСПУБЛИКА АНГОЛА', nameEn: 'Angola' },
  { code: '028', alpha2: 'AG', alpha3: 'ATG', nameRu: 'АНТИГУА И БАРБУДА', nameFullRu: 'АНТИГУА И БАРБУДА', nameEn: 'Antigua and Barbuda' },
  { code: '031', alpha2: 'AZ', alpha3: 'AZE', nameRu: 'АЗЕРБАЙДЖАН', nameFullRu: 'РЕСПУБЛИКА АЗЕРБАЙДЖАН', nameEn: 'Azerbaijan' },
  { code: '032', alpha2: 'AR', alpha3: 'ARG', nameRu: 'АРГЕНТИНА', nameFullRu: 'АРГЕНТИНСКАЯ РЕСПУБЛИКА', nameEn: 'Argentina' },
  { code: '036', alpha2: 'AU', alpha3: 'AUS', nameRu: 'АВСТРАЛИЯ', nameFullRu: 'АВСТРАЛИЯ', nameEn: 'Australia' },
  { code: '040', alpha2: 'AT', alpha3: 'AUT', nameRu: 'АВСТРИЯ', nameFullRu: 'АВСТРИЙСКАЯ РЕСПУБЛИКА', nameEn: 'Austria' },
  { code: '044', alpha2: 'BS', alpha3: 'BHS', nameRu: 'БАГАМЫ', nameFullRu: 'СОДРУЖЕСТВО БАГАМ', nameEn: 'Bahamas' },
  { code: '048', alpha2: 'BH', alpha3: 'BHR', nameRu: 'БАХРЕЙН', nameFullRu: 'КОРОЛЕВСТВО БАХРЕЙН', nameEn: 'Bahrain' },
  { code: '050', alpha2: 'BD', alpha3: 'BGD', nameRu: 'БАНГЛАДЕШ', nameFullRu: 'НАРОДНАЯ РЕСПУБЛИКА БАНГЛАДЕШ', nameEn: 'Bangladesh' },
  { code: '051', alpha2: 'AM', alpha3: 'ARM', nameRu: 'АРМЕНИЯ', nameFullRu: 'РЕСПУБЛИКА АРМЕНИЯ', nameEn: 'Armenia' },
  { code: '052', alpha2: 'BB', alpha3: 'BRB', nameRu: 'БАРБАДОС', nameFullRu: 'БАРБАДОС', nameEn: 'Barbados' },
  { code: '056', alpha2: 'BE', alpha3: 'BEL', nameRu: 'БЕЛЬГИЯ', nameFullRu: 'КОРОЛЕВСТВО БЕЛЬГИЯ', nameEn: 'Belgium' },
  { code: '060', alpha2: 'BM', alpha3: 'BMU', nameRu: 'БЕРМУДЫ', nameFullRu: 'БЕРМУДЫ', nameEn: 'Bermuda' },
  { code: '064', alpha2: 'BT', alpha3: 'BTN', nameRu: 'БУТАН', nameFullRu: 'КОРОЛЕВСТВО БУТАН', nameEn: 'Bhutan' },
  { code: '068', alpha2: 'BO', alpha3: 'BOL', nameRu: 'БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО', nameFullRu: 'МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО БОЛИВИЯ', nameEn: 'Bolivia, Plurinational State of' },
  { code: '070', alpha2: 'BA', alpha3: 'BIH', nameRu: 'БОСНИЯ И ГЕРЦЕГОВИНА', nameFullRu: 'БОСНИЯ И ГЕРЦЕГОВИНА', nameEn: 'Bosnia and Herzegovina' },
  { code: '072', alpha2: 'BW', alpha3: 'BWA', nameRu: 'БОТСВАНА', nameFullRu: 'РЕСПУБЛИКА БОТСВАНА', nameEn: 'Botswana' },
  { code: '074', alpha2: 'BV', alpha3: 'BVT', nameRu: 'ОСТРОВ БУВЕ', nameFullRu: 'ОСТРОВ БУВЕ', nameEn: 'Bouvet Island' },
  { code: '076', alpha2: 'BR', alpha3: 'BRA', nameRu: 'БРАЗИЛИЯ', nameFullRu: 'ФЕДЕРАТИВНАЯ РЕСПУБЛИКА БРАЗИЛИЯ', nameEn: 'Brazil' },
  { code: '084', alpha2: 'BZ', alpha3: 'BLZ', nameRu: 'БЕЛИЗ', nameFullRu: 'БЕЛИЗ', nameEn: 'Belize' },
  { code: '086', alpha2: 'IO', alpha3: 'IOT', nameRu: 'БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ', nameFullRu: 'БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ', nameEn: 'British Indian Ocean Territory' },
  { code: '090', alpha2: 'SB', alpha3: 'SLB', nameRu: 'СОЛОМОНОВЫ ОСТРОВА', nameFullRu: 'СОЛОМОНОВЫ ОСТРОВА', nameEn: 'Solomon Islands' },
  { code: '092', alpha2: 'VG', alpha3: 'VGB', nameRu: 'ВИРГИНСКИЕ ОСТРОВА, БРИТАНСКИЕ', nameFullRu: 'БРИТАНСКИЕ ВИРГИНСКИЕ ОСТРОВА', nameEn: 'Virgin Islands, British' },
  { code: '096', alpha2: 'BN', alpha3: 'BRN', nameRu: 'БРУНЕЙ-ДАРУССАЛАМ', nameFullRu: 'БРУНЕЙ-ДАРУССАЛАМ', nameEn: 'Brunei Darussalam' },
  { code: '100', alpha2: 'BG', alpha3: 'BGR', nameRu: 'БОЛГАРИЯ', nameFullRu: 'РЕСПУБЛИКА БОЛГАРИЯ', nameEn: 'Bulgaria' },
  { code: '104', alpha2: 'MM', alpha3: 'MMR', nameRu: 'МЬЯНМА', nameFullRu: 'РЕСПУБЛИКА СОЮЗ МЬЯНМА', nameEn: 'Myanmar' },
  { code: '108', alpha2: 'BI', alpha3: 'BDI', nameRu: 'БУРУНДИ', nameFullRu: 'РЕСПУБЛИКА БУРУНДИ', nameEn: 'Burundi' },
  { code: '112', alpha2: 'BY', alpha3: 'BLR', nameRu: 'БЕЛАРУСЬ', nameFullRu: 'РЕСПУБЛИКА БЕЛАРУСЬ', nameEn: 'Belarus' },
  { code: '116', alpha2: 'KH', alpha3: 'KHM', nameRu: 'КАМБОДЖА', nameFullRu: 'КОРОЛЕВСТВО КАМБОДЖА', nameEn: 'Cambodia' },
  { code: '120', alpha2: 'CM', alpha3: 'CMR', nameRu: 'КАМЕРУН', nameFullRu: 'РЕСПУБЛИКА КАМЕРУН', nameEn: 'Cameroon' },
  { code: '124', alpha2: 'CA', alpha3: 'CAN', nameRu: 'КАНАДА', nameFullRu: 'КАНАДА', nameEn: 'Canada' },
  { code: '132', alpha2: 'CV', alpha3: 'CPV', nameRu: 'КАБО-ВЕРДЕ', nameFullRu: 'РЕСПУБЛИКА КАБО-ВЕРДЕ', nameEn: 'Cabo Verde' },
  { code: '136', alpha2: 'KY', alpha3: 'CYM', nameRu: 'КАЙМАНОВЫ ОСТРОВА', nameFullRu: 'КАЙМАНОВЫ ОСТРОВА', nameEn: 'Cayman Islands' },
  { code: '140', alpha2: 'CF', alpha3: 'CAF', nameRu: 'ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА', nameFullRu: 'ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА', nameEn: 'Central African Republic' },
  { code: '144', alpha2: 'LK', alpha3: 'LKA', nameRu: 'ШРИ-ЛАНКА', nameFullRu: 'ДЕМОКРАТИЧЕСКАЯ СОЦИАЛИСТИЧЕСКАЯ РЕСПУБЛИКА ШРИ-ЛАНКА', nameEn: 'Sri Lanka' },
  { code: '148', alpha2: 'TD', alpha3: 'TCD', nameRu: 'ЧАД', nameFullRu: 'РЕСПУБЛИКА ЧАД', nameEn: 'Chad' },
  { code: '152', alpha2: 'CL', alpha3: 'CHL', nameRu: 'ЧИЛИ', nameFullRu: 'РЕСПУБЛИКА ЧИЛИ', nameEn: 'Chile' },
  { code: '156', alpha2: 'CN', alpha3: 'CHN', nameRu: 'КИТАЙ', nameFullRu: 'КИТАЙСКАЯ НАРОДНАЯ РЕСПУБЛИКА', nameEn: 'China' },
  { code: '158', alpha2: 'TW', alpha3: 'TWN', nameRu: 'ТАЙВАНЬ (КИТАЙ)', nameFullRu: 'ТАЙВАНЬ (КИТАЙ)', nameEn: 'Taiwan, Province of China' },
  { code: '162', alpha2: 'CX', alpha3: 'CXR', nameRu: 'ОСТРОВ РОЖДЕСТВА', nameFullRu: 'ОСТРОВ РОЖДЕСТВА', nameEn: 'Christmas Island' },
  { code: '166', alpha2: 'CC', alpha3: 'CCK', nameRu: 'КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА', nameFullRu: 'КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА', nameEn: 'Cocos (Keeling) Islands' },
  { code: '170', alpha2: 'CO', alpha3: 'COL', nameRu: 'КОЛУМБИЯ', nameFullRu: 'РЕСПУБЛИКА КОЛУМБИЯ', nameEn: 'Colombia' },
  { code: '174', alpha2: 'KM', alpha3: 'COM', nameRu: 'КОМОРЫ', nameFullRu: 'СОЮЗ КОМОРЫ', nameEn: 'Comoros' },
  { code: '175', alpha2: 'YT', alpha3: 'MYT', nameRu: 'МАЙОТТА', nameFullRu: 'МАЙОТТА', nameEn: 'Mayotte' },
  { code: '178', alpha2: 'CG', alpha3: 'COG', nameRu: 'КОНГО', nameFullRu: 'РЕСПУБЛИКА КОНГО', nameEn: 'Congo' },
  { code: '180', alpha2: 'CD', alpha3: 'COD', nameRu: 'КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', nameFullRu: 'ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА КОНГО', nameEn: 'Congo, the Democratic Republic of the' },
  { code: '184', alpha2: 'CK', alpha3: 'COK', nameRu: 'ОСТРОВА КУКА', nameFullRu: 'ОСТРОВА КУКА', nameEn: 'Cook Islands' },
  { code: '188', alpha2: 'CR', alpha3: 'CRI', nameRu: 'КОСТА-РИКА', nameFullRu: 'РЕСПУБЛИКА КОСТА-РИКА', nameEn: 'Costa Rica' },
  { code: '191', alpha2: 'HR', alpha3: 'HRV', nameRu: 'ХОРВАТИЯ', nameFullRu: 'РЕСПУБЛИКА ХОРВАТИЯ', nameEn: 'Croatia' },
  { code: '192', alpha2: 'CU', alpha3: 'CUB', nameRu: 'КУБА', nameFullRu: 'РЕСПУБЛИКА КУБА', nameEn: 'Cuba' },
  { code: '196', alpha2: 'CY', alpha3: 'CYP', nameRu: 'КИПР', nameFullRu: 'РЕСПУБЛИКА КИПР', nameEn: 'Cyprus' },
  { code: '203', alpha2: 'CZ', alpha3: 'CZE', nameRu: 'ЧЕХИЯ', nameFullRu: 'ЧЕШСКАЯ РЕСПУБЛИКА', nameEn: 'Czechia' },
  { code: '204', alpha2: 'BJ', alpha3: 'BEN', nameRu: 'БЕНИН', nameFullRu: 'РЕСПУБЛИКА БЕНИН', nameEn: 'Benin' },
  { code: '208', alpha2: 'DK', alpha3: 'DNK', nameRu: 'ДАНИЯ', nameFullRu: 'КОРОЛЕВСТВО ДАНИЯ', nameEn: 'Denmark' },
  { code: '212', alpha2: 'DM', alpha3: 'DMA', nameRu: 'ДОМИНИКА', nameFullRu: 'СОДРУЖЕСТВО ДОМИНИКИ', nameEn: 'Dominica' },
  { code: '214', alpha2: 'DO', alpha3: 'DOM', nameRu: 'ДОМИНИКАНСКАЯ РЕСПУБЛИКА', nameFullRu: 'ДОМИНИКАНСКАЯ РЕСПУБЛИКА', nameEn: 'Dominican Republic' },
  { code: '218', alpha2: 'EC', alpha3: 'ECU', nameRu: 'ЭКВАДОР', nameFullRu: 'РЕСПУБЛИКА ЭКВАДОР', nameEn: 'Ecuador' },
  { code: '222', alpha2: 'SV', alpha3: 'SLV', nameRu: 'ЭЛЬ-САЛЬВАДОР', nameFullRu: 'РЕСПУБЛИКА ЭЛЬ-САЛЬВАДОР', nameEn: 'El Salvador' },
  { code: '226', alpha2: 'GQ', alpha3: 'GNQ', nameRu: 'ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ', nameFullRu: 'РЕСПУБЛИКА ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ', nameEn: 'Equatorial Guinea' },
  { code: '231', alpha2: 'ET', alpha3: 'ETH', nameRu: 'ЭФИОПИЯ', nameFullRu: 'ФЕДЕРАТИВНАЯ ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА ЭФИОПИЯ', nameEn: 'Ethiopia' },
  { code: '232', alpha2: 'ER', alpha3: 'ERI', nameRu: 'ЭРИТРЕЯ', nameFullRu: 'ГОСУДАРСТВО ЭРИТРЕЯ', nameEn: 'Eritrea' },
  { code: '233', alpha2: 'EE', alpha3: 'EST', nameRu: 'ЭСТОНИЯ', nameFullRu: 'ЭСТОНСКАЯ РЕСПУБЛИКА', nameEn: 'Estonia' },
  { code: '234', alpha2: 'FO', alpha3: 'FRO', nameRu: 'ФАРЕРСКИЕ ОСТРОВА', nameFullRu: 'ФАРЕРСКИЕ ОСТРОВА', nameEn: 'Faroe Islands' },
  { code: '238', alpha2: 'FK', alpha3: 'FLK', nameRu: 'ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)', nameFullRu: 'ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)', nameEn: 'Falkland Islands (Malvinas)' },
  { code: '239', alpha2: 'GS', alpha3: 'SGS', nameRu: 'ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА', nameFullRu: 'ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА', nameEn: 'South Georgia and the South Sandwich Islands' },
  { code: '242', alpha2: 'FJ', alpha3: 'FJI', nameRu: 'ФИДЖИ', nameFullRu: 'РЕСПУБЛИКА ФИДЖИ', nameEn: 'Fiji' },
  { code: '246', alpha2: 'FI', alpha3: 'FIN', nameRu: 'ФИНЛЯНДИЯ', nameFullRu: 'ФИНЛЯНДСКАЯ РЕСПУБЛИКА', nameEn: 'Finland' },
  { code: '248', alpha2: 'AX', alpha3: 'ALA', nameRu: 'ОЛАНДСКИЕ ОСТРОВА', nameFullRu: 'ОЛАНДСКИЕ ОСТРОВА', nameEn: 'Åland Islands' },
  { code: '250', alpha2: 'FR', alpha3: 'FRA', nameRu: 'ФРАНЦИЯ', nameFullRu: 'ФРАНЦУЗСКАЯ РЕСПУБЛИКА', nameEn: 'France' },
  { code: '254', alpha2: 'GF', alpha3: 'GUF', nameRu: 'ФРАНЦУЗСКАЯ ГВИАНА', nameFullRu: 'ФРАНЦУЗСКАЯ ГВИАНА', nameEn: 'French Guiana' },
  { code: '258', alpha2: 'PF', alpha3: 'PYF', nameRu: 'ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ', nameFullRu: 'ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ', nameEn: 'French Polynesia' },
  { code: '260', alpha2: 'TF', alpha3: 'ATF', nameRu: 'ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ', nameFullRu: 'ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ', nameEn: 'French Southern Territories' },
  { code: '262', alpha2: 'DJ', alpha3: 'DJI', nameRu: 'ДЖИБУТИ', nameFullRu: 'РЕСПУБЛИКА ДЖИБУТИ', nameEn: 'Djibouti' },
  { code: '266', alpha2: 'GA', alpha3: 'GAB', nameRu: 'ГАБОН', nameFullRu: 'ГАБОНСКАЯ РЕСПУБЛИКА', nameEn: 'Gabon' },
  { code: '268', alpha2: 'GE', alpha3: 'GEO', nameRu: 'ГРУЗИЯ', nameFullRu: 'ГРУЗИЯ', nameEn: 'Georgia' },
  { code: '270', alpha2: 'GM', alpha3: 'GMB', nameRu: 'ГАМБИЯ', nameFullRu: 'РЕСПУБЛИКА ГАМБИЯ', nameEn: 'Gambia' },
  { code: '275', alpha2: 'PS', alpha3: 'PSE', nameRu: 'ПАЛЕСТИНА, ГОСУДАРСТВО', nameFullRu: 'ГОСУДАРСТВО ПАЛЕСТИНА', nameEn: 'Palestine, State of' },
  { code: '276', alpha2: 'DE', alpha3: 'DEU', nameRu: 'ГЕРМАНИЯ', nameFullRu: 'ФЕДЕРАТИВНАЯ РЕСПУБЛИКА ГЕРМАНИЯ', nameEn: 'Germany' },
  { code: '288', alpha2: 'GH', alpha3: 'GHA', nameRu: 'ГАНА', nameFullRu: 'РЕСПУБЛИКА ГАНА', nameEn: 'Ghana' },
  { code: '292', alpha2: 'GI', alpha3: 'GIB', nameRu: 'ГИБРАЛТАР', nameFullRu: 'ГИБРАЛТАР', nameEn: 'Gibraltar' },
  { code: '296', alpha2: 'KI', alpha3: 'KIR', nameRu: 'КИРИБАТИ', nameFullRu: 'РЕСПУБЛИКА КИРИБАТИ', nameEn: 'Kiribati' },
  { code: '300', alpha2: 'GR', alpha3: 'GRC', nameRu: 'ГРЕЦИЯ', nameFullRu: 'ГРЕЧЕСКАЯ РЕСПУБЛИКА', nameEn: 'Greece' },
  { code: '304', alpha2: 'GL', alpha3: 'GRL', nameRu: 'ГРЕНЛАНДИЯ', nameFullRu: 'ГРЕНЛАНДИЯ', nameEn: 'Greenland' },
  { code: '308', alpha2: 'GD', alpha3: 'GRD', nameRu: 'ГРЕНАДА', nameFullRu: 'ГРЕНАДА', nameEn: 'Grenada' },
  { code: '312', alpha2: 'GP', alpha3: 'GLP', nameRu: 'ГВАДЕЛУПА', nameFullRu: 'ГВАДЕЛУПА', nameEn: 'Guadeloupe' },
  { code: '316', alpha2: 'GU', alpha3: 'GUM', nameRu: 'ГУАМ', nameFullRu: 'ГУАМ', nameEn: 'Guam' },
  { code: '320', alpha2: 'GT', alpha3: 'GTM', nameRu: 'ГВАТЕМАЛА', nameFullRu: 'РЕСПУБЛИКА ГВАТЕМАЛА', nameEn: 'Guatemala' },
  { code: '324', alpha2: 'GN', alpha3: 'GIN', nameRu: 'ГВИНЕЯ', nameFullRu: 'ГВИНЕЙСКАЯ РЕСПУБЛИКА', nameEn: 'Guinea' },
  { code: '328', alpha2: 'GY', alpha3: 'GUY', nameRu: 'ГАЙАНА', nameFullRu: 'РЕСПУБЛИКА ГАЙАНА', nameEn: 'Guyana' },
  { code: '332', alpha2: 'HT', alpha3: 'HTI', nameRu: 'ГАИТИ', nameFullRu: 'РЕСПУБЛИКА ГАИТИ', nameEn: 'Haiti' },
  { code: '334', alpha2: 'HM', alpha3: 'HMD', nameRu: 'ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД', nameFullRu: 'ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД', nameEn: 'Heard Island and McDonald Islands' },
  { code: '336', alpha2: 'VA', alpha3: 'VAT', nameRu: 'ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО-ГОРОД ВАТИКАН)', nameFullRu: 'ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО-ГОРОД ВАТИКАН)', nameEn: 'Holy See (Vatican City State)' },
  { code: '340', alpha2: 'HN', alpha3: 'HND', nameRu: 'ГОНДУРАС', nameFullRu: 'РЕСПУБЛИКА ГОНДУРАС', nameEn: 'Honduras' },
  { code: '344', alpha2: 'HK', alpha3: 'HKG', nameRu: 'ГОНКОНГ', nameFullRu: 'ГОНКОНГ СПЕЦИАЛЬНЫЙ АДМИНИСТРАТИВНЫЙ РАЙОН КИТАЯ', nameEn: 'Hong Kong' },
  { code: '348', alpha2: 'HU', alpha3: 'HUN', nameRu: 'ВЕНГРИЯ', nameFullRu: 'ВЕНГРИЯ', nameEn: 'Hungary' },
  { code: '352', alpha2: 'IS', alpha3: 'ISL', nameRu: 'ИСЛАНДИЯ', nameFullRu: 'ИСЛАНДИЯ', nameEn: 'Iceland' },
  { code: '356', alpha2: 'IN', alpha3: 'IND', nameRu: 'ИНДИЯ', nameFullRu: 'РЕСПУБЛИКА ИНДИЯ', nameEn: 'India' },
  { code: '360', alpha2: 'ID', alpha3: 'IDN', nameRu: 'ИНДОНЕЗИЯ', nameFullRu: 'РЕСПУБЛИКА ИНДОНЕЗИЯ', nameEn: 'Indonesia' },
  { code: '364', alpha2: 'IR', alpha3: 'IRN', nameRu: 'ИРАН, ИСЛАМСКАЯ РЕСПУБЛИКА', nameFullRu: 'ИСЛАМСКАЯ РЕСПУБЛИКА ИРАН', nameEn: 'Iran, Islamic Republic of' },
  { code: '368', alpha2: 'IQ', alpha3: 'IRQ', nameRu: 'ИРАК', nameFullRu: 'РЕСПУБЛИКА ИРАК', nameEn: 'Iraq' },
  { code: '372', alpha2: 'IE', alpha3: 'IRL', nameRu: 'ИРЛАНДИЯ', nameFullRu: 'ИРЛАНДИЯ', nameEn: 'Ireland' },
  { code: '376', alpha2: 'IL', alpha3: 'ISR', nameRu: 'ИЗРАИЛЬ', nameFullRu: 'ГОСУДАРСТВО ИЗРАИЛЬ', nameEn: 'Israel' },
  { code: '380', alpha2: 'IT', alpha3: 'ITA', nameRu: 'ИТАЛИЯ', nameFullRu: 'ИТАЛЬЯНСКАЯ РЕСПУБЛИКА', nameEn: 'Italy' },
  { code: '384', alpha2: 'CI', alpha3: 'CIV', nameRu: 'КОТ Д\'ИВУАР', nameFullRu: 'РЕСПУБЛИКА КОТ Д\'ИВУАР', nameEn: 'Côte d\'Ivoire' },
  { code: '388', alpha2: 'JM', alpha3: 'JAM', nameRu: 'ЯМАЙКА', nameFullRu: 'ЯМАЙКА', nameEn: 'Jamaica' },
  { code: '392', alpha2: 'JP', alpha3: 'JPN', nameRu: 'ЯПОНИЯ', nameFullRu: 'ЯПОНИЯ', nameEn: 'Japan' },
  { code: '398', alpha2: 'KZ', alpha3: 'KAZ', nameRu: 'КАЗАХСТАН', nameFullRu: 'РЕСПУБЛИКА КАЗАХСТАН', nameEn: 'Kazakhstan' },
  { code: '400', alpha2: 'JO', alpha3: 'JOR', nameRu: 'ИОРДАНИЯ', nameFullRu: 'ИОРДАНСКОЕ ХАШИМИТСКОЕ КОРОЛЕВСТВО', nameEn: 'Jordan' },
  { code: '404', alpha2: 'KE', alpha3: 'KEN', nameRu: 'КЕНИЯ', nameFullRu: 'РЕСПУБЛИКА КЕНИЯ', nameEn: 'Kenya' },
  { code: '408', alpha2: 'KP', alpha3: 'PRK', nameRu: 'КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', nameFullRu: 'КОРЕЙСКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', nameEn: 'Korea, Democratic People\'s Republic of' },
  { code: '410', alpha2: 'KR', alpha3: 'KOR', nameRu: 'КОРЕЯ, РЕСПУБЛИКА', nameFullRu: 'РЕСПУБЛИКА КОРЕЯ', nameEn: 'Korea, Republic of' },
  { code: '414', alpha2: 'KW', alpha3: 'KWT', nameRu: 'КУВЕЙТ', nameFullRu: 'ГОСУДАРСТВО КУВЕЙТ', nameEn: 'Kuwait' },
  { code: '417', alpha2: 'KG', alpha3: 'KGZ', nameRu: 'КЫРГЫЗСТАН', nameFullRu: 'КЫРГЫЗСКАЯ РЕСПУБЛИКА', nameEn: 'Kyrgyzstan' },
  { code: '418', alpha2: 'LA', alpha3: 'LAO', nameRu: 'ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', nameFullRu: 'ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', nameEn: 'Lao People\'s Democratic Republic' },
  { code: '422', alpha2: 'LB', alpha3: 'LBN', nameRu: 'ЛИВАН', nameFullRu: 'ЛИВАНСКАЯ РЕСПУБЛИКА', nameEn: 'Lebanon' },
  { code: '426', alpha2: 'LS', alpha3: 'LSO', nameRu: 'ЛЕСОТО', nameFullRu: 'КОРОЛЕВСТВО ЛЕСОТО', nameEn: 'Lesotho' },
  { code: '428', alpha2: 'LV', alpha3: 'LVA', nameRu: 'ЛАТВИЯ', nameFullRu: 'ЛАТВИЙСКАЯ РЕСПУБЛИКА', nameEn: 'Latvia' },
  { code: '430', alpha2: 'LR', alpha3: 'LBR', nameRu: 'ЛИБЕРИЯ', nameFullRu: 'РЕСПУБЛИКА ЛИБЕРИЯ', nameEn: 'Liberia' },
  { code: '434', alpha2: 'LY', alpha3: 'LBY', nameRu: 'ЛИВИЯ', nameFullRu: 'ЛИВИЯ', nameEn: 'Libya' },
  { code: '438', alpha2: 'LI', alpha3: 'LIE', nameRu: 'ЛИХТЕНШТЕЙН', nameFullRu: 'КНЯЖЕСТВО ЛИХТЕНШТЕЙН', nameEn: 'Liechtenstein' },
  { code: '440', alpha2: 'LT', alpha3: 'LTU', nameRu: 'ЛИТВА', nameFullRu: 'ЛИТОВСКАЯ РЕСПУБЛИКА', nameEn: 'Lithuania' },
  { code: '442', alpha2: 'LU', alpha3: 'LUX', nameRu: 'ЛЮКСЕМБУРГ', nameFullRu: 'ВЕЛИКОЕ ГЕРЦОГСТВО ЛЮКСЕМБУРГ', nameEn: 'Luxembourg' },
  { code: '446', alpha2: 'MO', alpha3: 'MAC', nameRu: 'МАКАО', nameFullRu: 'МАКАО', nameEn: 'Macao' },
  { code: '450', alpha2: 'MG', alpha3: 'MDG', nameRu: 'МАДАГАСКАР', nameFullRu: 'РЕСПУБЛИКА МАДАГАСКАР', nameEn: 'Madagascar' },
  { code: '454', alpha2: 'MW', alpha3: 'MWI', nameRu: 'МАЛАВИ', nameFullRu: 'РЕСПУБЛИКА МАЛАВИ', nameEn: 'Malawi' },
  { code: '458', alpha2: 'MY', alpha3: 'MYS', nameRu: 'МАЛАЙЗИЯ', nameFullRu: 'МАЛАЙЗИЯ', nameEn: 'Malaysia' },
  { code: '462', alpha2: 'MV', alpha3: 'MDV', nameRu: 'МАЛЬДИВЫ', nameFullRu: 'МАЛЬДИВСКАЯ РЕСПУБЛИКА', nameEn: 'Maldives' },
  { code: '466', alpha2: 'ML', alpha3: 'MLI', nameRu: 'МАЛИ', nameFullRu: 'РЕСПУБЛИКА МАЛИ', nameEn: 'Mali' },
  { code: '470', alpha2: 'MT', alpha3: 'MLT', nameRu: 'МАЛЬТА', nameFullRu: 'РЕСПУБЛИКА МАЛЬТА', nameEn: 'Malta' },
  { code: '474', alpha2: 'MQ', alpha3: 'MTQ', nameRu: 'МАРТИНИКА', nameFullRu: 'МАРТИНИКА', nameEn: 'Martinique' },
  { code: '478', alpha2: 'MR', alpha3: 'MRT', nameRu: 'МАВРИТАНИЯ', nameFullRu: 'ИСЛАМСКАЯ РЕСПУБЛИКА МАВРИТАНИЯ', nameEn: 'Mauritania' },
  { code: '480', alpha2: 'MU', alpha3: 'MUS', nameRu: 'МАВРИКИЙ', nameFullRu: 'РЕСПУБЛИКА МАВРИКИЙ', nameEn: 'Mauritius' },
  { code: '484', alpha2: 'MX', alpha3: 'MEX', nameRu: 'МЕКСИКА', nameFullRu: 'МЕКСИКАНСКИЕ СОЕДИНЕННЫЕ ШТАТЫ', nameEn: 'Mexico' },
  { code: '492', alpha2: 'MC', alpha3: 'MCO', nameRu: 'МОНАКО', nameFullRu: 'КНЯЖЕСТВО МОНАКО', nameEn: 'Monaco' },
  { code: '496', alpha2: 'MN', alpha3: 'MNG', nameRu: 'МОНГОЛИЯ', nameFullRu: 'МОНГОЛИЯ', nameEn: 'Mongolia' },
  { code: '498', alpha2: 'MD', alpha3: 'MDA', nameRu: 'МОЛДОВА, РЕСПУБЛИКА', nameFullRu: 'РЕСПУБЛИКА МОЛДОВА', nameEn: 'Moldova, Republic of' },
  { code: '499', alpha2: 'ME', alpha3: 'MNE', nameRu: 'ЧЕРНОГОРИЯ', nameFullRu: 'ЧЕРНОГОРИЯ', nameEn: 'Montenegro' },
  { code: '500', alpha2: 'MS', alpha3: 'MSR', nameRu: 'МОНТСЕРРАТ', nameFullRu: 'МОНТСЕРРАТ', nameEn: 'Montserrat' },
  { code: '504', alpha2: 'MA', alpha3: 'MAR', nameRu: 'МАРОККО', nameFullRu: 'КОРОЛЕВСТВО МАРОККО', nameEn: 'Morocco' },
  { code: '508', alpha2: 'MZ', alpha3: 'MOZ', nameRu: 'МОЗАМБИК', nameFullRu: 'РЕСПУБЛИКА МОЗАМБИК', nameEn: 'Mozambique' },
  { code: '512', alpha2: 'OM', alpha3: 'OMN', nameRu: 'ОМАН', nameFullRu: 'СУЛТАНАТ ОМАН', nameEn: 'Oman' },
  { code: '516', alpha2: 'NA', alpha3: 'NAM', nameRu: 'НАМИБИЯ', nameFullRu: 'РЕСПУБЛИКА НАМИБИЯ', nameEn: 'Namibia' },
  { code: '520', alpha2: 'NR', alpha3: 'NRU', nameRu: 'НАУРУ', nameFullRu: 'РЕСПУБЛИКА НАУРУ', nameEn: 'Nauru' },
  { code: '524', alpha2: 'NP', alpha3: 'NPL', nameRu: 'НЕПАЛ', nameFullRu: 'ФЕДЕРАТИВНАЯ ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА НЕПАЛ', nameEn: 'Nepal' },
  { code: '528', alpha2: 'NL', alpha3: 'NLD', nameRu: 'НИДЕРЛАНДЫ', nameFullRu: 'КОРОЛЕВСТВО НИДЕРЛАНДОВ', nameEn: 'Netherlands' },
  { code: '531', alpha2: 'CW', alpha3: 'CUW', nameRu: 'КЮРАСАО', nameFullRu: 'КЮРАСАО', nameEn: 'Curaçao' },
  { code: '533', alpha2: 'AW', alpha3: 'ABW', nameRu: 'АРУБА', nameFullRu: 'АРУБА', nameEn: 'Aruba' },
  { code: '534', alpha2: 'SX', alpha3: 'SXM', nameRu: 'СЕН-МАРТЕН (НИДЕРЛАНДСКАЯ ЧАСТЬ)', nameFullRu: 'СЕН-МАРТЕН (НИДЕРЛАНДСКАЯ ЧАСТЬ)', nameEn: 'Sint Maarten (Dutch part)' },
  { code: '535', alpha2: 'BQ', alpha3: 'BES', nameRu: 'БОНЭЙР, СИНТ-ЭСТАТИУС И САБА', nameFullRu: 'БОНЭЙР, СИНТ-ЭСТАТИУС И САБА', nameEn: 'Bonaire, Sint Eustatius and Saba' },
  { code: '540', alpha2: 'NC', alpha3: 'NCL', nameRu: 'НОВАЯ КАЛЕДОНИЯ', nameFullRu: 'НОВАЯ КАЛЕДОНИЯ', nameEn: 'New Caledonia' },
  { code: '548', alpha2: 'VU', alpha3: 'VUT', nameRu: 'ВАНУАТУ', nameFullRu: 'РЕСПУБЛИКА ВАНУАТУ', nameEn: 'Vanuatu' },
  { code: '554', alpha2: 'NZ', alpha3: 'NZL', nameRu: 'НОВАЯ ЗЕЛАНДИЯ', nameFullRu: 'НОВАЯ ЗЕЛАНДИЯ', nameEn: 'New Zealand' },
  { code: '558', alpha2: 'NI', alpha3: 'NIC', nameRu: 'НИКАРАГУА', nameFullRu: 'РЕСПУБЛИКА НИКАРАГУА', nameEn: 'Nicaragua' },
  { code: '562', alpha2: 'NE', alpha3: 'NER', nameRu: 'НИГЕР', nameFullRu: 'РЕСПУБЛИКА НИГЕР', nameEn: 'Niger' },
  { code: '566', alpha2: 'NG', alpha3: 'NGA', nameRu: 'НИГЕРИЯ', nameFullRu: 'ФЕДЕРАТИВНАЯ РЕСПУБЛИКА НИГЕРИЯ', nameEn: 'Nigeria' },
  { code: '570', alpha2: 'NU', alpha3: 'NIU', nameRu: 'НИУЭ', nameFullRu: 'НИУЭ', nameEn: 'Niue' },
  { code: '574', alpha2: 'NF', alpha3: 'NFK', nameRu: 'ОСТРОВ НОРФОЛК', nameFullRu: 'ОСТРОВ НОРФОЛК', nameEn: 'Norfolk Island' },
  { code: '578', alpha2: 'NO', alpha3: 'NOR', nameRu: 'НОРВЕГИЯ', nameFullRu: 'КОРОЛЕВСТВО НОРВЕГИЯ', nameEn: 'Norway' },
  { code: '580', alpha2: 'MP', alpha3: 'MNP', nameRu: 'СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА', nameFullRu: 'СОДРУЖЕСТВО СЕВЕРНЫХ МАРИАНСКИХ ОСТРОВОВ', nameEn: 'Northern Mariana Islands' },
  { code: '581', alpha2: 'UM', alpha3: 'UMI', nameRu: 'МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ', nameFullRu: 'МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ', nameEn: 'United States Minor Outlying Islands' },
  { code: '583', alpha2: 'FM', alpha3: 'FSM', nameRu: 'МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ', nameFullRu: 'ФЕДЕРАТИВНЫЕ ШТАТЫ МИКРОНЕЗИИ', nameEn: 'Micronesia, Federated States of' },
  { code: '584', alpha2: 'MH', alpha3: 'MHL', nameRu: 'МАРШАЛЛОВЫ ОСТРОВА', nameFullRu: 'РЕСПУБЛИКА МАРШАЛЛОВЫ ОСТРОВА', nameEn: 'Marshall Islands' },
  { code: '585', alpha2: 'PW', alpha3: 'PLW', nameRu: 'ПАЛАУ', nameFullRu: 'РЕСПУБЛИКА ПАЛАУ', nameEn: 'Palau' },
  { code: '586', alpha2: 'PK', alpha3: 'PAK', nameRu: 'ПАКИСТАН', nameFullRu: 'ИСЛАМСКАЯ РЕСПУБЛИКА ПАКИСТАН', nameEn: 'Pakistan' },
  { code: '591', alpha2: 'PA', alpha3: 'PAN', nameRu: 'ПАНАМА', nameFullRu: 'РЕСПУБЛИКА ПАНАМА', nameEn: 'Panama' },
  { code: '598', alpha2: 'PG', alpha3: 'PNG', nameRu: 'ПАПУА НОВАЯ ГВИНЕЯ', nameFullRu: 'НЕЗАВИСИМОЕ ГОСУДАРСТВО ПАПУА НОВАЯ ГВИНЕЯ', nameEn: 'Papua New Guinea' },
  { code: '600', alpha2: 'PY', alpha3: 'PRY', nameRu: 'ПАРАГВАЙ', nameFullRu: 'РЕСПУБЛИКА ПАРАГВАЙ', nameEn: 'Paraguay' },
  { code: '604', alpha2: 'PE', alpha3: 'PER', nameRu: 'ПЕРУ', nameFullRu: 'РЕСПУБЛИКА ПЕРУ', nameEn: 'Peru' },
  { code: '608', alpha2: 'PH', alpha3: 'PHL', nameRu: 'ФИЛИППИНЫ', nameFullRu: 'РЕСПУБЛИКА ФИЛИППИНЫ', nameEn: 'Philippines' },
  { code: '612', alpha2: 'PN', alpha3: 'PCN', nameRu: 'ПИТКЕРН', nameFullRu: 'ПИТКЕРН', nameEn: 'Pitcairn' },
  { code: '616', alpha2: 'PL', alpha3: 'POL', nameRu: 'ПОЛЬША', nameFullRu: 'РЕСПУБЛИКА ПОЛЬША', nameEn: 'Poland' },
  { code: '620', alpha2: 'PT', alpha3: 'PRT', nameRu: 'ПОРТУГАЛИЯ', nameFullRu: 'ПОРТУГАЛЬСКАЯ РЕСПУБЛИКА', nameEn: 'Portugal' },
  { code: '624', alpha2: 'GW', alpha3: 'GNB', nameRu: 'ГВИНЕЯ-БИСАУ', nameFullRu: 'РЕСПУБЛИКА ГВИНЕЯ-БИСАУ', nameEn: 'Guinea-Bissau' },
  { code: '626', alpha2: 'TL', alpha3: 'TLS', nameRu: 'ТИМОР-ЛЕСТЕ', nameFullRu: 'ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА ТИМОР-ЛЕСТЕ', nameEn: 'Timor-Leste' },
  { code: '630', alpha2: 'PR', alpha3: 'PRI', nameRu: 'ПУЭРТО-РИКО', nameFullRu: 'ПУЭРТО-РИКО', nameEn: 'Puerto Rico' },
  { code: '634', alpha2: 'QA', alpha3: 'QAT', nameRu: 'КАТАР', nameFullRu: 'ГОСУДАРСТВО КАТАР', nameEn: 'Qatar' },
  { code: '638', alpha2: 'RE', alpha3: 'REU', nameRu: 'РЕЮНЬОН', nameFullRu: 'РЕЮНЬОН', nameEn: 'Réunion' },
  { code: '642', alpha2: 'RO', alpha3: 'ROU', nameRu: 'РУМЫНИЯ', nameFullRu: 'РУМЫНИЯ', nameEn: 'Romania' },
  { code: '643', alpha2: 'RU', alpha3: 'RUS', nameRu: 'РОССИЯ', nameFullRu: 'РОССИЙСКАЯ ФЕДЕРАЦИЯ', nameEn: 'Russian Federation' },
  { code: '646', alpha2: 'RW', alpha3: 'RWA', nameRu: 'РУАНДА', nameFullRu: 'РУАНДИЙСКАЯ РЕСПУБЛИКА', nameEn: 'Rwanda' },
  { code: '652', alpha2: 'BL', alpha3: 'BLM', nameRu: 'СЕН-БАРТЕЛЕМИ', nameFullRu: 'СЕН-БАРТЕЛЕМИ', nameEn: 'Saint Barthélemy' },
  { code: '654', alpha2: 'SH', alpha3: 'SHN', nameRu: 'СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ', nameFullRu: 'СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ', nameEn: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: '659', alpha2: 'KN', alpha3: 'KNA', nameRu: 'СЕНТ-КИТС И НЕВИС', nameFullRu: 'СЕНТ-КИТС И НЕВИС', nameEn: 'Saint Kitts and Nevis' },
  { code: '660', alpha2: 'AI', alpha3: 'AIA', nameRu: 'АНГИЛЬЯ', nameFullRu: 'АНГИЛЬЯ', nameEn: 'Anguilla' },
  { code: '662', alpha2: 'LC', alpha3: 'LCA', nameRu: 'СЕНТ-ЛЮСИЯ', nameFullRu: 'СЕНТ-ЛЮСИЯ', nameEn: 'Saint Lucia' },
  { code: '663', alpha2: 'MF', alpha3: 'MAF', nameRu: 'СЕН-МАРТЕН (ФРАНЦУЗСКАЯ ЧАСТЬ)', nameFullRu: 'СЕН-МАРТЕН (ФРАНЦУЗСКАЯ ЧАСТЬ)', nameEn: 'Saint Martin (French part)' },
  { code: '666', alpha2: 'PM', alpha3: 'SPM', nameRu: 'СЕНТ-ПЬЕР И МИКЕЛОН', nameFullRu: 'СЕНТ-ПЬЕР И МИКЕЛОН', nameEn: 'Saint Pierre and Miquelon' },
  { code: '670', alpha2: 'VC', alpha3: 'VCT', nameRu: 'СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ', nameFullRu: 'СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ', nameEn: 'Saint Vincent and the Grenadines' },
  { code: '674', alpha2: 'SM', alpha3: 'SMR', nameRu: 'САН-МАРИНО', nameFullRu: 'РЕСПУБЛИКА САН-МАРИНО', nameEn: 'San Marino' },
  { code: '678', alpha2: 'ST', alpha3: 'STP', nameRu: 'САН-ТОМЕ И ПРИНСИПИ', nameFullRu: 'ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА САН-ТОМЕ И ПРИНСИПИ', nameEn: 'Sao Tome and Principe' },
  { code: '682', alpha2: 'SA', alpha3: 'SAU', nameRu: 'САУДОВСКАЯ АРАВИЯ', nameFullRu: 'КОРОЛЕВСТВО САУДОВСКАЯ АРАВИЯ', nameEn: 'Saudi Arabia' },
  { code: '686', alpha2: 'SN', alpha3: 'SEN', nameRu: 'СЕНЕГАЛ', nameFullRu: 'РЕСПУБЛИКА СЕНЕГАЛ', nameEn: 'Senegal' },
  { code: '688', alpha2: 'RS', alpha3: 'SRB', nameRu: 'СЕРБИЯ', nameFullRu: 'РЕСПУБЛИКА СЕРБИЯ', nameEn: 'Serbia' },
  { code: '690', alpha2: 'SC', alpha3: 'SYC', nameRu: 'СЕЙШЕЛЫ', nameFullRu: 'РЕСПУБЛИКА СЕЙШЕЛЫ', nameEn: 'Seychelles' },
  { code: '694', alpha2: 'SL', alpha3: 'SLE', nameRu: 'СЬЕРРА-ЛЕОНЕ', nameFullRu: 'РЕСПУБЛИКА СЬЕРРА-ЛЕОНЕ', nameEn: 'Sierra Leone' },
  { code: '702', alpha2: 'SG', alpha3: 'SGP', nameRu: 'СИНГАПУР', nameFullRu: 'РЕСПУБЛИКА СИНГАПУР', nameEn: 'Singapore' },
  { code: '703', alpha2: 'SK', alpha3: 'SVK', nameRu: 'СЛОВАКИЯ', nameFullRu: 'СЛОВАЦКАЯ РЕСПУБЛИКА', nameEn: 'Slovakia' },
  { code: '704', alpha2: 'VN', alpha3: 'VNM', nameRu: 'ВЬЕТНАМ', nameFullRu: 'СОЦИАЛИСТИЧЕСКАЯ РЕСПУБЛИКА ВЬЕТНАМ', nameEn: 'Viet Nam' },
  { code: '705', alpha2: 'SI', alpha3: 'SVN', nameRu: 'СЛОВЕНИЯ', nameFullRu: 'РЕСПУБЛИКА СЛОВЕНИЯ', nameEn: 'Slovenia' },
  { code: '706', alpha2: 'SO', alpha3: 'SOM', nameRu: 'СОМАЛИ', nameFullRu: 'ФЕДЕРАТИВНАЯ РЕСПУБЛИКА СОМАЛИ', nameEn: 'Somalia' },
  { code: '710', alpha2: 'ZA', alpha3: 'ZAF', nameRu: 'ЮЖНАЯ АФРИКА', nameFullRu: 'ЮЖНО-АФРИКАНСКАЯ РЕСПУБЛИКА', nameEn: 'South Africa' },
  { code: '716', alpha2: 'ZW', alpha3: 'ZWE', nameRu: 'ЗИМБАБВЕ', nameFullRu: 'РЕСПУБЛИКА ЗИМБАБВЕ', nameEn: 'Zimbabwe' },
  { code: '724', alpha2: 'ES', alpha3: 'ESP', nameRu: 'ИСПАНИЯ', nameFullRu: 'КОРОЛЕВСТВО ИСПАНИЯ', nameEn: 'Spain' },
  { code: '728', alpha2: 'SS', alpha3: 'SSD', nameRu: 'ЮЖНЫЙ СУДАН', nameFullRu: 'РЕСПУБЛИКА ЮЖНЫЙ СУДАН', nameEn: 'South Sudan' },
  { code: '729', alpha2: 'SD', alpha3: 'SDN', nameRu: 'СУДАН', nameFullRu: 'РЕСПУБЛИКА СУДАН', nameEn: 'Sudan' },
  { code: '732', alpha2: 'EH', alpha3: 'ESH', nameRu: 'ЗАПАДНАЯ САХАРА', nameFullRu: 'ЗАПАДНАЯ САХАРА', nameEn: 'Western Sahara' },
  { code: '740', alpha2: 'SR', alpha3: 'SUR', nameRu: 'СУРИНАМ', nameFullRu: 'РЕСПУБЛИКА СУРИНАМ', nameEn: 'Suriname' },
  { code: '744', alpha2: 'SJ', alpha3: 'SJM', nameRu: 'ШПИЦБЕРГЕН И ЯН-МАЙЕН', nameFullRu: 'ШПИЦБЕРГЕН И ЯН-МАЙЕН', nameEn: 'Svalbard and Jan Mayen' },
  { code: '748', alpha2: 'SZ', alpha3: 'SWZ', nameRu: 'ЭСВАТИНИ', nameFullRu: 'КОРОЛЕВСТВО ЭСВАТИНИ', nameEn: 'Eswatini' },
  { code: '752', alpha2: 'SE', alpha3: 'SWE', nameRu: 'ШВЕЦИЯ', nameFullRu: 'КОРОЛЕВСТВО ШВЕЦИЯ', nameEn: 'Sweden' },
  { code: '756', alpha2: 'CH', alpha3: 'CHE', nameRu: 'ШВЕЙЦАРИЯ', nameFullRu: 'ШВЕЙЦАРСКАЯ КОНФЕДЕРАЦИЯ', nameEn: 'Switzerland' },
  { code: '760', alpha2: 'SY', alpha3: 'SYR', nameRu: 'СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА', nameFullRu: 'СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА', nameEn: 'Syrian Arab Republic' },
  { code: '762', alpha2: 'TJ', alpha3: 'TJK', nameRu: 'ТАДЖИКИСТАН', nameFullRu: 'РЕСПУБЛИКА ТАДЖИКИСТАН', nameEn: 'Tajikistan' },
  { code: '764', alpha2: 'TH', alpha3: 'THA', nameRu: 'ТАИЛАНД', nameFullRu: 'КОРОЛЕВСТВО ТАИЛАНД', nameEn: 'Thailand' },
  { code: '768', alpha2: 'TG', alpha3: 'TGO', nameRu: 'ТОГО', nameFullRu: 'ТОГОЛЕЗСКАЯ РЕСПУБЛИКА', nameEn: 'Togo' },
  { code: '772', alpha2: 'TK', alpha3: 'TKL', nameRu: 'ТОКЕЛАУ', nameFullRu: 'ТОКЕЛАУ', nameEn: 'Tokelau' },
  { code: '776', alpha2: 'TO', alpha3: 'TON', nameRu: 'ТОНГА', nameFullRu: 'КОРОЛЕВСТВО ТОНГА', nameEn: 'Tonga' },
  { code: '780', alpha2: 'TT', alpha3: 'TTO', nameRu: 'ТРИНИДАД И ТОБАГО', nameFullRu: 'РЕСПУБЛИКА ТРИНИДАД И ТОБАГО', nameEn: 'Trinidad and Tobago' },
  { code: '784', alpha2: 'AE', alpha3: 'ARE', nameRu: 'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ', nameFullRu: 'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ', nameEn: 'United Arab Emirates' },
  { code: '788', alpha2: 'TN', alpha3: 'TUN', nameRu: 'ТУНИС', nameFullRu: 'ТУНИССКАЯ РЕСПУБЛИКА', nameEn: 'Tunisia' },
  { code: '792', alpha2: 'TR', alpha3: 'TUR', nameRu: 'ТУРЦИЯ', nameFullRu: 'ТУРЕЦКАЯ РЕСПУБЛИКА', nameEn: 'Türkiye' },
  { code: '795', alpha2: 'TM', alpha3: 'TKM', nameRu: 'ТУРКМЕНИСТАН', nameFullRu: 'ТУРКМЕНИСТАН', nameEn: 'Turkmenistan' },
  { code: '796', alpha2: 'TC', alpha3: 'TCA', nameRu: 'ОСТРОВА ТЕРКС И КАЙКОС', nameFullRu: 'ОСТРОВА ТЕРКС И КАЙКОС', nameEn: 'Turks and Caicos Islands' },
  { code: '798', alpha2: 'TV', alpha3: 'TUV', nameRu: 'ТУВАЛУ', nameFullRu: 'ТУВАЛУ', nameEn: 'Tuvalu' },
  { code: '800', alpha2: 'UG', alpha3: 'UGA', nameRu: 'УГАНДА', nameFullRu: 'РЕСПУБЛИКА УГАНДА', nameEn: 'Uganda' },
  { code: '804', alpha2: 'UA', alpha3: 'UKR', nameRu: 'УКРАИНА', nameFullRu: 'УКРАИНА', nameEn: 'Ukraine' },
  { code: '807', alpha2: 'MK', alpha3: 'MKD', nameRu: 'СЕВЕРНАЯ МАКЕДОНИЯ', nameFullRu: 'РЕСПУБЛИКА СЕВЕРНАЯ МАКЕДОНИЯ', nameEn: 'North Macedonia' },
  { code: '818', alpha2: 'EG', alpha3: 'EGY', nameRu: 'ЕГИПЕТ', nameFullRu: 'АРАБСКАЯ РЕСПУБЛИКА ЕГИПЕТ', nameEn: 'Egypt' },
  { code: '826', alpha2: 'GB', alpha3: 'GBR', nameRu: 'СОЕДИНЕННОЕ КОРОЛЕВСТВО', nameFullRu: 'СОЕДИНЕННОЕ КОРОЛЕВСТВО ВЕЛИКОБРИТАНИИ И СЕВЕРНОЙ ИРЛАНДИИ', nameEn: 'United Kingdom' },
  { code: '831', alpha2: 'GG', alpha3: 'GGY', nameRu: 'ГЕРНСИ', nameFullRu: 'ГЕРНСИ', nameEn: 'Guernsey' },
  { code: '832', alpha2: 'JE', alpha3: 'JEY', nameRu: 'ДЖЕРСИ', nameFullRu: 'ДЖЕРСИ', nameEn: 'Jersey' },
  { code: '833', alpha2: 'IM', alpha3: 'IMN', nameRu: 'ОСТРОВ МЭН', nameFullRu: 'ОСТРОВ МЭН', nameEn: 'Isle of Man' },
  { code: '834', alpha2: 'TZ', alpha3: 'TZA', nameRu: 'ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА', nameFullRu: 'ОБЪЕДИНЕННАЯ РЕСПУБЛИКА ТАНЗАНИЯ', nameEn: 'Tanzania, United Republic of' },
  { code: '840', alpha2: 'US', alpha3: 'USA', nameRu: 'СОЕДИНЕННЫЕ ШТАТЫ', nameFullRu: 'СОЕДИНЕННЫЕ ШТАТЫ АМЕРИКИ', nameEn: 'United States' },
  { code: '850', alpha2: 'VI', alpha3: 'VIR', nameRu: 'ВИРГИНСКИЕ ОСТРОВА, США', nameFullRu: 'ВИРГИНСКИЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ', nameEn: 'Virgin Islands, U.S.' },
  { code: '854', alpha2: 'BF', alpha3: 'BFA', nameRu: 'БУРКИНА-ФАСО', nameFullRu: 'БУРКИНА-ФАСО', nameEn: 'Burkina Faso' },
  { code: '858', alpha2: 'UY', alpha3: 'URY', nameRu: 'УРУГВАЙ', nameFullRu: 'ВОСТОЧНАЯ РЕСПУБЛИКА УРУГВАЙ', nameEn: 'Uruguay' },
  { code: '860', alpha2: 'UZ', alpha3: 'UZB', nameRu: 'УЗБЕКИСТАН', nameFullRu: 'РЕСПУБЛИКА УЗБЕКИСТАН', nameEn: 'Uzbekistan' },
  { code: '862', alpha2: 'VE', alpha3: 'VEN', nameRu: 'ВЕНЕСУЭЛА БОЛИВАРИАНСКАЯ РЕСПУБЛИКА', nameFullRu: 'БОЛИВАРИАНСКАЯ РЕСПУБЛИКА ВЕНЕСУЭЛА', nameEn: 'Venezuela, Bolivarian Republic of' },
  { code: '876', alpha2: 'WF', alpha3: 'WLF', nameRu: 'УОЛЛИС И ФУТУНА', nameFullRu: 'УОЛЛИС И ФУТУНА', nameEn: 'Wallis and Futuna' },
  { code: '882', alpha2: 'WS', alpha3: 'WSM', nameRu: 'САМОА', nameFullRu: 'НЕЗАВИСИМОЕ ГОСУДАРСТВО САМОА', nameEn: 'Samoa' },
  { code: '887', alpha2: 'YE', alpha3: 'YEM', nameRu: 'ЙЕМЕН', nameFullRu: 'ЙЕМЕНСКАЯ РЕСПУБЛИКА', nameEn: 'Yemen' },
  { code: '894', alpha2: 'ZM', alpha3: 'ZMB', nameRu: 'ЗАМБИЯ', nameFullRu: 'РЕСПУБЛИКА ЗАМБИЯ', nameEn: 'Zambia' },
];

export const OKSMT_BY_CODE: ReadonlyMap<string, OksmtCountry> = new Map(
  OKSMT_COUNTRIES.map((c) => [c.code, c]),
);

export const OKSMT_SORTED_BY_NAME_RU: readonly OksmtCountry[] = [...OKSMT_COUNTRIES].sort(
  (a, b) => a.nameRu.localeCompare(b.nameRu, 'ru'),
);
